### ISSUE TITLE
ecp_internal.h is not described in documentation

### ISSUE THREAD

**Issue by RonEld** [ARMmbed/mbedtls#972]
The *ecp_internal.h* file is not described in the [doxygen generated API documentation](https://tls.mbed.org/api/files.html)

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-1469

**Comment by mpg** [comment]
This header is excluded in [mbedtls.doxygen][https://github.com/ARMmbed/mbedtls/blob/development/doxygen/mbedtls.doxyfile#L707], on the basis that files with `internal` in their name are not supposed to be part of the public API. I wish we were more consistent in naming, it can be a bit confusing for users if some `_internal.h` are public and some others are not.

**Comment by RonEld** [comment]
I understand, perhaps we should reconsider the way we support the ECP alternative implementation

**Comment by gilles-peskine-arm** [comment]
Resolved by PR #965

**Comment by gilles-peskine-arm** [comment]
@mpg It is useful to document the functions that must be implemented for alternative hardware implementations. Maybe we should have two different doxygen configurations, one for end-users and one for alternative implementers?

**Comment by mpg** [comment]
@gilles-peskine-arm I fully agree that it is useful to document those functions, and I agree with your fix in #965.

@RonEld I don't think we need to reconsider much, it's just the naming that is a bit sub-optimal, but we can't really change that now that it's published.

**Comment by yanesca** [comment]
@mpg I see now that it wasn't a very good choice for the naming, and I really regret that we forgot about the semantic consequences when we were discussing it.

**Comment by RonEld** [comment]
Hi @gilles-peskine-arm I have uploaded a [kb article](https://tls.mbed.org/kb/development/hw_acc_guidelines) with guidelines for alternative implementations. I think that the article, with the existing API documentation should be sufficient. 

@mpg I think that it is still not too late to change it, as:
1. It is in a branch that APIs could change
2. It is a new feature published, which I think it's still safe to change, I believe

**Comment by yanesca** [comment]
Hi @gilles-peskine-arm , @mpg and @RonEld ,

When last week I saw this issue, then I thought that we made a terrible mistake with naming back then. But the more I think about it, the more convinced I am that this was intentional and it is good as it is.

I see that it would be nice and comfortable to link to online doxygen documentation from our How-To articles, but
- No application or driver code should ever call these functions and they are not part of the public API
- Since they are not part of the public API, their documentation shouldn't be in the online public API documentation
-  You are all right that we need to explain these functions in detail, but I think we should do it separately in the Knowledge Base and Handbook articles or maybe in a blogpost, but not in the public API

What do you think?

**Comment by RonEld** [comment]
Hi @yanesca I think that since this file should be used by external users, implementing the alternative ecp module, I think it can't be declared internal, and although a KB article is good, I would expect this file to be explained in the regular API documentation (doxygen). The KB article explains guidelines, but will not explain what every API does.  
Although it is not a public API, it is still externally used.
